FROM node:20-alpine

WORKDIR /app

COPY ./frontend/package.json ./

COPY ./frontend/pnpm-lock.yaml ./

RUN corepack enable && pnpm i

COPY ./frontend/ .

# EXPOSE 4173
# RUN pnpm run build
# CMD ["pnpm", "run" "preview"]

EXPOSE 5173
CMD ["pnpm", "run", "dev"]

# PROD
# EXPOSE 3000
# CMD ["node",  "build"]